In [1]:
pip install scikit-multilearn

In [2]:
pip install liac-arff

Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas as pd
import numpy as np
import os

file_df = pd.read_csv('data/data_set_label.csv')

In [4]:
file_df

No       filename                                              Links  \
0      1   Travel_1.mp4  https://www.tiktok.com/@travelaholicgf/video/7...   
1      2   Travel_2.mp4  https://www.tiktok.com/@usfirster/video/731055...   
2      3   Travel_3.mp4  https://www.tiktok.com/@storiesfan/video/72901...   
3      4   Travel_4.mp4  https://www.tiktok.com/@traveloka.th/video/717...   
4      5   Travel_5.mp4  https://www.tiktok.com/@traveloka.th/video/721...   
..   ...            ...                                                ...   
791  296  Sport_296.mp4  https://www.tiktok.com/@yoga.waadkian/video/72...   
792  297  Sport_297.mp4  https://www.tiktok.com/@yoga.waadkian/video/72...   
793  298  Sport_298.mp4  https://www.tiktok.com/@yoga.waadkian/video/72...   
794  299  Sport_299.mp4  https://www.tiktok.com/@yoga.waadkian/video/72...   
795  300  Sport_300.mp4  https://www.tiktok.com/@yoga.waadkian/video/72...   

            main_label                 sub_label  \
0               Travel             Accommodation   
1               Travel             Accommodation   
2               Travel  Accommodation, Adventure   
3               Travel                 Adventure   
4               Travel                 Adventure   
..                 ...                       ...   
791  Sport and Fitness                      Yoga   
792  Sport and Fitness                      Yoga   
793  Sport and Fitness                      Yoga   
794  Sport and Fitness                      Yoga   
795  Sport and Fitness                      Yoga   

     Healthy Lifestyle and Weight Loss  Weight Lifting  Running  Yoga  \
0                                    0               0        0     0   
1                                    0               0        0     0   
2                                    0               0        0     0   
3                                    0               0        0     0   
4                                    0               0        0     0   
..                                 ...             ...      ...   ...   
791                                  0               0        0     1   
792                                  0               0        0     1   
793                                  0               0        0     1   
794                                  0               0        0     1   
795                                  0               0        0     1   

     Haircare  ...  Outfit  Accommodation  Adventure  Culture  Food and drink  \
0           0  ...       0              1          0        0               0   
1           0  ...       0              1          0        0               0   
2           0  ...       0              1          1        0               0   
3           0  ...       0              0          1        0               0   
4           0  ...       0              0          1        0               0   
..        ...  ...     ...            ...        ...      ...             ...   
791         0  ...       0              0          0        0               0   
792         0  ...       0              0          0        0               0   
793         0  ...       0              0          0        0               0   
794         0  ...       0              0          0        0               0   
795         0  ...       0              0          0        0               0   

       duration  frame_count  height  width  fps  
0     67.666667         2030    1024    576   30  
1     67.933333         2038    1024    576   30  
2     23.933333          718    1024    576   30  
3     78.300000         2349    1024    576   30  
4    104.200000         3126    1024    576   30  
..          ...          ...     ...    ...  ...  
791  207.400000         6222    1024    576   30  
792   87.966667         2639    1024    576   30  
793   20.266667          608    1024    576   30  
794   36.833333         1105    1024    576   30  
795   73.933333         2218    1

In [5]:
X = file_df.loc[:, ['filename']].to_numpy()
y = file_df.loc[:, ["Healthy Lifestyle and Weight Loss", "Weight Lifting", "Running", "Yoga", "Haircare", "Makeup", "Skincare", "Outfit", "Accommodation", "Adventure", "Culture", "Food and drink"]].to_numpy()


In [6]:
X

array([['Travel_1.mp4'],
       ['Travel_2.mp4'],
       ['Travel_3.mp4'],
       ['Travel_4.mp4'],
       ['Travel_5.mp4'],
       ['Travel_6.mp4'],
       ['Travel_7.mp4'],
       ['Travel_8.mp4'],
       ['Travel_9.mp4'],
       ['Travel_10.mp4'],
       ['Travel_11.mp4'],
       ['Travel_12.mp4'],
       ['Travel_47.mp4'],
       ['Travel_48.mp4'],
       ['Travel_13.mp4'],
       ['Travel_24.mp4'],
       ['Travel_15.mp4'],
       ['Travel_14.mp4'],
       ['Travel_16.mp4'],
       ['Travel_17.mp4'],
       ['Travel_19.mp4'],
       ['Travel_20.mp4'],
       ['Travel_21.mp4'],
       ['Travel_22.mp4'],
       ['Travel_23.mp4'],
       ['Beauty_1.mp4'],
       ['Sport_1.mp4'],
       ['Sport_2.mp4'],
       ['Sport_3.mp4'],
       ['Sport_4.mp4'],
       ['Sport_5.mp4'],
       ['Sport_8.mp4'],
       ['Sport_82.mp4'],
       ['Sport_9.mp4'],
       ['Beauty_2.mp4'],
       ['Beauty_3.mp4'],
       ['Beauty_4.mp4'],
       ['Beauty_5.mp4'],
       ['Beauty_6.mp4'],
       ['Beauty_

In [7]:
y

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [8]:
from skmultilearn.dataset import load_dataset
from skmultilearn.model_selection import iterative_train_test_split

#X, y, _, _ = load_dataset('scene', 'undivided')

X_train, y_train, X_test, y_test = iterative_train_test_split(X, y, test_size=0.1)
X_train, y_train, X_val, y_val = iterative_train_test_split(X, y, test_size=0.1)


In [9]:
X_train

array([['Travel_1.mp4'],
       ['Travel_3.mp4'],
       ['Travel_4.mp4'],
       ['Travel_6.mp4'],
       ['Travel_8.mp4'],
       ['Travel_10.mp4'],
       ['Travel_12.mp4'],
       ['Travel_48.mp4'],
       ['Travel_15.mp4'],
       ['Travel_16.mp4'],
       ['Travel_19.mp4'],
       ['Travel_22.mp4'],
       ['Sport_2.mp4'],
       ['Sport_4.mp4'],
       ['Sport_8.mp4'],
       ['Beauty_2.mp4'],
       ['Beauty_4.mp4'],
       ['Beauty_6.mp4'],
       ['Beauty_8.mp4'],
       ['Beauty_10.mp4'],
       ['Beauty_12.mp4'],
       ['Beauty_15.mp4'],
       ['Beauty_17.mp4'],
       ['Beauty_19.mp4'],
       ['Beauty_22.mp4'],
       ['Beauty_23.mp4'],
       ['Sport_11.mp4'],
       ['Sport_13.mp4'],
       ['Sport_15.mp4'],
       ['Beauty_26.mp4'],
       ['Beauty_28.mp4'],
       ['Beauty_30.mp4'],
       ['Sport_18.mp4'],
       ['Sport_20.mp4'],
       ['Sport_22.mp4'],
       ['Sport_23.mp4'],
       ['Sport_25.mp4'],
       ['Sport_27.mp4'],
       ['Sport_29.mp4'],
       ['Tr

In [10]:
X_test

array([['Travel_2.mp4'],
       ['Travel_3.mp4'],
       ['Travel_5.mp4'],
       ['Travel_7.mp4'],
       ['Travel_9.mp4'],
       ['Travel_11.mp4'],
       ['Travel_47.mp4'],
       ['Travel_13.mp4'],
       ['Travel_24.mp4'],
       ['Travel_14.mp4'],
       ['Travel_17.mp4'],
       ['Travel_20.mp4'],
       ['Travel_21.mp4'],
       ['Travel_23.mp4'],
       ['Beauty_1.mp4'],
       ['Sport_1.mp4'],
       ['Sport_3.mp4'],
       ['Sport_5.mp4'],
       ['Sport_82.mp4'],
       ['Beauty_3.mp4'],
       ['Beauty_5.mp4'],
       ['Beauty_7.mp4'],
       ['Beauty_9.mp4'],
       ['Beauty_11.mp4'],
       ['Beauty_15.mp4'],
       ['Beauty_18.mp4'],
       ['Beauty_20.mp4'],
       ['Beauty_21.mp4'],
       ['Sport_10.mp4'],
       ['Sport_12.mp4'],
       ['Sport_14.mp4'],
       ['Sport_97.mp4'],
       ['Beauty_25.mp4'],
       ['Beauty_27.mp4'],
       ['Beauty_29.mp4'],
       ['Sport_17.mp4'],
       ['Sport_19.mp4'],
       ['Sport_21.mp4'],
       ['Sport_24.mp4'],
       ['Sp

In [11]:
X_val

array([['Travel_2.mp4'],
       ['Travel_5.mp4'],
       ['Travel_7.mp4'],
       ['Travel_9.mp4'],
       ['Travel_11.mp4'],
       ['Travel_47.mp4'],
       ['Travel_13.mp4'],
       ['Travel_24.mp4'],
       ['Travel_14.mp4'],
       ['Travel_17.mp4'],
       ['Travel_20.mp4'],
       ['Travel_21.mp4'],
       ['Travel_23.mp4'],
       ['Beauty_1.mp4'],
       ['Sport_1.mp4'],
       ['Sport_3.mp4'],
       ['Sport_5.mp4'],
       ['Sport_82.mp4'],
       ['Sport_9.mp4'],
       ['Beauty_3.mp4'],
       ['Beauty_5.mp4'],
       ['Beauty_7.mp4'],
       ['Beauty_9.mp4'],
       ['Beauty_11.mp4'],
       ['Beauty_16.mp4'],
       ['Beauty_18.mp4'],
       ['Beauty_20.mp4'],
       ['Beauty_21.mp4'],
       ['Sport_10.mp4'],
       ['Sport_12.mp4'],
       ['Sport_14.mp4'],
       ['Sport_97.mp4'],
       ['Beauty_25.mp4'],
       ['Beauty_27.mp4'],
       ['Beauty_29.mp4'],
       ['Sport_17.mp4'],
       ['Sport_19.mp4'],
       ['Sport_21.mp4'],
       ['Sport_24.mp4'],
       ['Spo

In [12]:
y_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [13]:
y_test

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0,

In [14]:
y_val

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0,

In [15]:
from skmultilearn.model_selection.measures import get_combination_wise_output_matrix
from collections import Counter

pd.DataFrame({
    'train': Counter(str(combination) for row in get_combination_wise_output_matrix(y_train, order=2) for combination in row),
    'test' : Counter(str(combination) for row in get_combination_wise_output_matrix(y_test, order=2) for combination in row),
    'validation' : Counter(str(combination) for row in get_combination_wise_output_matrix(y_val, order=2) for combination in row)
}).T.fillna(0.0)

(8, 8)  (8, 9)  (9, 9)  (10, 10)  (9, 10)  (10, 11)  (9, 11)  \
train         29.0    14.0   155.0      49.0     42.0      16.0     26.0   
test           3.0     2.0    17.0       5.0      5.0       1.0      3.0   
validation     3.0     1.0    17.0       5.0      5.0       1.0      3.0   

            (11, 11)  (0, 0)  (0, 1)  ...  (2, 2)  (6, 6)  (3, 3)  (8, 11)  \
train           51.0    68.0    13.0  ...    68.0    59.0    66.0      6.0   
test             6.0     8.0     1.0  ...     8.0     7.0     7.0      1.0   
validation       6.0     8.0     1.0  ...     8.0     7.0     7.0      1.0   

            (4, 4)  (0, 2)  (0, 3)  (5, 6)  (5, 7)  (1, 2)  
train          7.0     2.0     4.0     2.0     1.0     1.0  
test           1.0     0.0     0.0     0.0     0.0     0.0  
validation     1.0     0.0     1.0     0.0     0.0     0.0  

[3 rows x 23 columns]

In [16]:
X_train.shape[0], X_test.shape[0], X_val.shape[0]

(715, 81, 81)

In [17]:
y_train.shape[0], y_test.shape[0], y_val.shape[0]

(715, 81, 81)

In [18]:
#Define Column name
train_column = ["filename"]

# Create a DataFrame
train_df = pd.DataFrame(X_train, columns = train_column)

# Display the DataFrame
print(train_df)

          filename
0     Travel_1.mp4
1     Travel_3.mp4
2     Travel_4.mp4
3     Travel_6.mp4
4     Travel_8.mp4
..             ...
710  Sport_296.mp4
711  Sport_297.mp4
712  Sport_298.mp4
713  Sport_299.mp4
714  Sport_300.mp4

[715 rows x 1 columns]


In [19]:
# Add a new column with the same length as the DataFrame
train_df["data_split"] = ["train"] * len(train_df)

# Display the DataFrame with the new column
print(train_df)

          filename data_split
0     Travel_1.mp4      train
1     Travel_3.mp4      train
2     Travel_4.mp4      train
3     Travel_6.mp4      train
4     Travel_8.mp4      train
..             ...        ...
710  Sport_296.mp4      train
711  Sport_297.mp4      train
712  Sport_298.mp4      train
713  Sport_299.mp4      train
714  Sport_300.mp4      train

[715 rows x 2 columns]


In [20]:
#Define Column name
test_column = ["filename"]

# Create a DataFrame
test_df = pd.DataFrame(X_test, columns = test_column)

# Display the DataFrame
print(test_df)

         filename
0    Travel_2.mp4
1    Travel_3.mp4
2    Travel_5.mp4
3    Travel_7.mp4
4    Travel_9.mp4
..            ...
76  Sport_165.mp4
77   Sport_30.mp4
78  Sport_220.mp4
79  Sport_222.mp4
80  Sport_224.mp4

[81 rows x 1 columns]


In [21]:
# Add a new column with the same length as the DataFrame
test_df["data_split"] = ["test"] * len(test_df)

# Display the DataFrame with the new column
print(test_df)

         filename data_split
0    Travel_2.mp4       test
1    Travel_3.mp4       test
2    Travel_5.mp4       test
3    Travel_7.mp4       test
4    Travel_9.mp4       test
..            ...        ...
76  Sport_165.mp4       test
77   Sport_30.mp4       test
78  Sport_220.mp4       test
79  Sport_222.mp4       test
80  Sport_224.mp4       test

[81 rows x 2 columns]


In [22]:
#Define Column name
val_column = ["filename"]

# Create a DataFrame
val_df = pd.DataFrame(X_val, columns = test_column)

# Display the DataFrame
print(val_df)

         filename
0    Travel_2.mp4
1    Travel_5.mp4
2    Travel_7.mp4
3    Travel_9.mp4
4   Travel_11.mp4
..            ...
76  Sport_163.mp4
77  Sport_165.mp4
78   Sport_30.mp4
79  Sport_220.mp4
80  Sport_222.mp4

[81 rows x 1 columns]


In [23]:
# Add a new column with the same length as the DataFrame
val_df["data_split"] = ["validation"] * len(val_df)

# Display the DataFrame with the new column
print(val_df)

         filename  data_split
0    Travel_2.mp4  validation
1    Travel_5.mp4  validation
2    Travel_7.mp4  validation
3    Travel_9.mp4  validation
4   Travel_11.mp4  validation
..            ...         ...
76  Sport_163.mp4  validation
77  Sport_165.mp4  validation
78   Sport_30.mp4  validation
79  Sport_220.mp4  validation
80  Sport_222.mp4  validation

[81 rows x 2 columns]


In [24]:
concat_df = pd.concat([train_df, test_df, val_df], axis=0)

# Display the concatenated DataFrame along columns
print(concat_df)

         filename  data_split
0    Travel_1.mp4       train
1    Travel_3.mp4       train
2    Travel_4.mp4       train
3    Travel_6.mp4       train
4    Travel_8.mp4       train
..            ...         ...
76  Sport_163.mp4  validation
77  Sport_165.mp4  validation
78   Sport_30.mp4  validation
79  Sport_220.mp4  validation
80  Sport_222.mp4  validation

[877 rows x 2 columns]


In [25]:
# Inner join
join_df = pd.merge(file_df, concat_df, on = "filename")
print(join_df)

      No       filename                                              Links  \
0      1   Travel_1.mp4  https://www.tiktok.com/@travelaholicgf/video/7...   
1      2   Travel_2.mp4  https://www.tiktok.com/@usfirster/video/731055...   
2      2   Travel_2.mp4  https://www.tiktok.com/@usfirster/video/731055...   
3      3   Travel_3.mp4  https://www.tiktok.com/@storiesfan/video/72901...   
4      3   Travel_3.mp4  https://www.tiktok.com/@storiesfan/video/72901...   
..   ...            ...                                                ...   
872  296  Sport_296.mp4  https://www.tiktok.com/@yoga.waadkian/video/72...   
873  297  Sport_297.mp4  https://www.tiktok.com/@yoga.waadkian/video/72...   
874  298  Sport_298.mp4  https://www.tiktok.com/@yoga.waadkian/video/72...   
875  299  Sport_299.mp4  https://www.tiktok.com/@yoga.waadkian/video/72...   
876  300  Sport_300.mp4  https://www.tiktok.com/@yoga.waadkian/video/72...   

            main_label                 sub_label  \
0          

In [26]:
# Specify the file path where you want to save the CSV file
csv_file_path = 'data/data_set_label.csv'

# Export the DataFrame to a CSV file
join_df.to_csv(csv_file_path, index=False)

print(f'DataFrame exported to CSV file: {csv_file_path}')

DataFrame exported to CSV file: data/data_set_label.csv
